package com.railway.enums;

public enum UserStatus {
    CHOOSE_FROM_REGION, CHOOSE_TO_REGION, CHOOSE_DATE, BUY_TICKET,
    CHOOSE_FROMST_FOR_SEND_LOCATION,
    MY_TICKET , ENTERED_REYS_MENU, CHOOSE_WAGON, ENTER_DATA_OF_CUSTOMERS, FILL_DATA_CUSTOMER, FILL_BALANCE
}
